
"""add_raw_data_and_family

Revision ID: 087aa6017ffc
Revises: ffe10738d011
Create Date: 2026-02-11 20:49:03.541525

"""
from alembic import op
import sqlalchemy as sa
from app.core.db_types import JSON


# revision identifiers, used by Alembic.
revision = '087aa6017ffc'
down_revision = 'aabd97e3448e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add columns to unified_persons
    with op.batch_alter_table('unified_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_info', sa.String(length=500), nullable=True, comment='家庭成员信息'))
        batch_op.add_column(sa.Column('raw_data', JSON(), nullable=True, comment='原始API数据'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unified_persons', schema=None) as batch_op:
        batch_op.drop_column('raw_data')
        batch_op.drop_column('family_info')

    # ### end Alembic commands ###
