"""remove_auto_download_strategy_column

Revision ID: 51a3d3495948
Revises: b93c5d19cfae
Create Date: 2026-02-25 21:37:51.583503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a3d3495948'
down_revision: Union[str, None] = 'b93c5d19cfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'auto_download_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('auto_download_strategy', sa.VARCHAR(length=20), nullable=False, server_default='smart'))
    # ### end Alembic commands ###
