"""Add UnifiedPerson and Credit models

Revision ID: aabd97e3448e
Revises: 7a46fefe5863
Create Date: 2026-02-10 21:30:19.039849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import app.core.db_types

# revision identifiers, used by Alembic.
revision: str = 'aabd97e3448e'
down_revision: Union[str, None] = '7a46fefe5863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_persons',
    sa.Column('tmdb_id', sa.Integer(), nullable=True, comment='TMDB ID'),
    sa.Column('imdb_id', sa.String(length=20), nullable=True, comment='IMDB ID'),
    sa.Column('douban_id', sa.String(length=20), nullable=True, comment='豆瓣 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='姓名'),
    sa.Column('other_names', app.core.db_types.JSON(), nullable=True, comment='别名/译名 (JSON数组)'),
    sa.Column('biography', sa.Text(), nullable=True, comment='简介'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('deathday', sa.Date(), nullable=True, comment='逝世日期'),
    sa.Column('place_of_birth', sa.String(length=255), nullable=True, comment='出生地'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='性别 1:女, 2:男, 0:未知'),
    sa.Column('homepage', sa.String(length=500), nullable=True, comment='个人主页'),
    sa.Column('known_for_department', sa.String(length=50), nullable=True, comment='知名于'),
    sa.Column('popularity', sa.Float(), nullable=True, comment='热度值'),
    sa.Column('profile_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('detail_loaded', sa.Boolean(), nullable=False, comment='详情是否已加载'),
    sa.Column('detail_loaded_at', sa.DateTime(timezone=True), nullable=True, comment='详情加载时间'),
    sa.Column('metadata_source', sa.String(length=20), nullable=True, comment='元数据来源'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unified_persons_douban_id'), 'unified_persons', ['douban_id'], unique=True)
    op.create_index(op.f('ix_unified_persons_id'), 'unified_persons', ['id'], unique=False)
    op.create_index(op.f('ix_unified_persons_imdb_id'), 'unified_persons', ['imdb_id'], unique=True)
    op.create_index(op.f('ix_unified_persons_name'), 'unified_persons', ['name'], unique=False)
    op.create_index(op.f('ix_unified_persons_tmdb_id'), 'unified_persons', ['tmdb_id'], unique=True)
    
    op.create_table('movie_credits',
    sa.Column('movie_id', sa.Integer(), nullable=False, comment='电影ID'),
    sa.Column('person_id', sa.Integer(), nullable=False, comment='人员ID'),
    sa.Column('job', sa.String(length=50), nullable=False, comment='职位: Actor, Director, Writer, etc.'),
    sa.Column('character', sa.String(length=500), nullable=True, comment='角色名'),
    sa.Column('order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['movie_id'], ['unified_movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['unified_persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_credits_id'), 'movie_credits', ['id'], unique=False)
    op.create_index(op.f('ix_movie_credits_job'), 'movie_credits', ['job'], unique=False)
    op.create_index(op.f('ix_movie_credits_movie_id'), 'movie_credits', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_credits_person_id'), 'movie_credits', ['person_id'], unique=False)
    
    op.create_table('tv_series_credits',
    sa.Column('tv_series_id', sa.Integer(), nullable=False, comment='电视剧ID'),
    sa.Column('person_id', sa.Integer(), nullable=False, comment='人员ID'),
    sa.Column('job', sa.String(length=50), nullable=False, comment='职位'),
    sa.Column('character', sa.String(length=500), nullable=True, comment='角色名'),
    sa.Column('order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['person_id'], ['unified_persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tv_series_id'], ['unified_tv_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tv_series_credits_id'), 'tv_series_credits', ['id'], unique=False)
    op.create_index(op.f('ix_tv_series_credits_job'), 'tv_series_credits', ['job'], unique=False)
    op.create_index(op.f('ix_tv_series_credits_person_id'), 'tv_series_credits', ['person_id'], unique=False)
    op.create_index(op.f('ix_tv_series_credits_tv_series_id'), 'tv_series_credits', ['tv_series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tv_series_credits_tv_series_id'), table_name='tv_series_credits')
    op.drop_index(op.f('ix_tv_series_credits_person_id'), table_name='tv_series_credits')
    op.drop_index(op.f('ix_tv_series_credits_job'), table_name='tv_series_credits')
    op.drop_index(op.f('ix_tv_series_credits_id'), table_name='tv_series_credits')
    op.drop_table('tv_series_credits')
    op.drop_index(op.f('ix_movie_credits_person_id'), table_name='movie_credits')
    op.drop_index(op.f('ix_movie_credits_movie_id'), table_name='movie_credits')
    op.drop_index(op.f('ix_movie_credits_job'), table_name='movie_credits')
    op.drop_index(op.f('ix_movie_credits_id'), table_name='movie_credits')
    op.drop_table('movie_credits')
    op.drop_index(op.f('ix_unified_persons_tmdb_id'), table_name='unified_persons')
    op.drop_index(op.f('ix_unified_persons_name'), table_name='unified_persons')
    op.drop_index(op.f('ix_unified_persons_imdb_id'), table_name='unified_persons')
    op.drop_index(op.f('ix_unified_persons_id'), table_name='unified_persons')
    op.drop_index(op.f('ix_unified_persons_douban_id'), table_name='unified_persons')
    op.drop_table('unified_persons')
    # ### end Alembic commands ###
