# -*- coding: utf-8 -*-
"""
媒体服务器常量定义（Jellyfin/Emby/Plex）
"""

# 媒体服务器类型
MEDIA_SERVER_TYPE_JELLYFIN = "jellyfin"
MEDIA_SERVER_TYPE_EMBY = "emby"
MEDIA_SERVER_TYPE_PLEX = "plex"

MEDIA_SERVER_TYPES = [
    MEDIA_SERVER_TYPE_JELLYFIN,
    MEDIA_SERVER_TYPE_EMBY,
    MEDIA_SERVER_TYPE_PLEX,
]

# 媒体服务器状态
MEDIA_SERVER_STATUS_ONLINE = "online"
MEDIA_SERVER_STATUS_OFFLINE = "offline"
MEDIA_SERVER_STATUS_ERROR = "error"

# 媒体库类型（通用）
MEDIA_SERVER_LIBRARY_TYPE_MOVIES = "movies"
MEDIA_SERVER_LIBRARY_TYPE_TVSHOWS = "tvshows"
MEDIA_SERVER_LIBRARY_TYPE_MUSIC = "music"
MEDIA_SERVER_LIBRARY_TYPE_BOOKS = "books"

# 同步间隔配置
DEFAULT_WATCH_HISTORY_SYNC_INTERVAL = 60  # 60分钟
MIN_SYNC_INTERVAL_MINUTES = 10
MAX_SYNC_INTERVAL_MINUTES = 1440  # 24小时

# 观看完成阈值（90%）
WATCH_COMPLETE_THRESHOLD = 0.9

# Jellyfin 默认端口
JELLYFIN_DEFAULT_PORT = 8096
# Emby 默认端口
EMBY_DEFAULT_PORT = 8096
# Plex 默认端口
PLEX_DEFAULT_PORT = 32400
