# -*- coding: utf-8 -*-
"""
资源识别相关常量
"""

# 识别状态常量
IDENTIFICATION_STATUS_UNIDENTIFIED = "unidentified"      # 未识别
IDENTIFICATION_STATUS_IDENTIFIED = "identified"          # 已识别
IDENTIFICATION_STATUS_FAILED = "failed"                  # 识别失败

IDENTIFICATION_STATUSES = [
    IDENTIFICATION_STATUS_UNIDENTIFIED,
    IDENTIFICATION_STATUS_IDENTIFIED,
    IDENTIFICATION_STATUS_FAILED,
]

# 识别源类型
IDENTIFICATION_SOURCE_LOCAL_CACHE = "local_cache"  # 本地缓存
IDENTIFICATION_SOURCE_MTEAM_DOUBAN = "mteam_douban"  # MTeam豆瓣接口
IDENTIFICATION_SOURCE_DOUBAN_API = "douban_api"  # 豆瓣API（通过douban_id）
IDENTIFICATION_SOURCE_DOUBAN_SEARCH = "douban_search"  # 豆瓣搜索（通过标题+年份）
IDENTIFICATION_SOURCE_TMDB_BY_IMDB = "tmdb_by_imdb"  # TMDB精确匹配（通过imdb_id）
IDENTIFICATION_SOURCE_TMDB_SEARCH = "tmdb_search"  # TMDB模糊搜索（通过标题+年份）

# 默认识别优先级顺序
DEFAULT_IDENTIFICATION_PRIORITY = [
    IDENTIFICATION_SOURCE_LOCAL_CACHE,  # 1. 本地缓存（最快，0成本）
    IDENTIFICATION_SOURCE_MTEAM_DOUBAN,  # 2. MTeam豆瓣接口（准确，免费）
    IDENTIFICATION_SOURCE_DOUBAN_API,  # 3. 豆瓣API直接查询（需要douban_id）
    IDENTIFICATION_SOURCE_TMDB_BY_IMDB,  # 4. TMDB精确匹配（需要imdb_id）
    IDENTIFICATION_SOURCE_DOUBAN_SEARCH,  # 5. 豆瓣搜索（可能不准确）
    IDENTIFICATION_SOURCE_TMDB_SEARCH,  # 6. TMDB搜索（可能不准确，最后兜底）
]

# 识别源显示名称
IDENTIFICATION_SOURCE_NAMES = {
    IDENTIFICATION_SOURCE_LOCAL_CACHE: "本地缓存",
    IDENTIFICATION_SOURCE_MTEAM_DOUBAN: "MTeam豆瓣接口",
    IDENTIFICATION_SOURCE_DOUBAN_API: "豆瓣API",
    IDENTIFICATION_SOURCE_DOUBAN_SEARCH: "豆瓣搜索",
    IDENTIFICATION_SOURCE_TMDB_BY_IMDB: "TMDB精确匹配",
    IDENTIFICATION_SOURCE_TMDB_SEARCH: "TMDB搜索",
}

# 识别源描述
IDENTIFICATION_SOURCE_DESCRIPTIONS = {
    IDENTIFICATION_SOURCE_LOCAL_CACHE: "优先从本地数据库查找已识别的资源（基于豆瓣ID或IMDB ID）",
    IDENTIFICATION_SOURCE_MTEAM_DOUBAN: "通过MTeam站点的豆瓣接口获取详细信息（免费，准确）",
    IDENTIFICATION_SOURCE_DOUBAN_API: "通过豆瓣ID直接查询豆瓣API（需要资源已有豆瓣ID）",
    IDENTIFICATION_SOURCE_DOUBAN_SEARCH: "通过标题和年份搜索豆瓣（可能不准确）",
    IDENTIFICATION_SOURCE_TMDB_BY_IMDB: "通过IMDB ID查询TMDB（需要资源已有IMDB ID）",
    IDENTIFICATION_SOURCE_TMDB_SEARCH: "通过标题和年份搜索TMDB（可能不准确，最后兜底）",
}
