# -*- coding: utf-8 -*-
"""
任务调度相关常量
"""

# 任务类型
TASK_TYPE_PT_RESOURCE_SYNC = "pt_resource_sync"
TASK_TYPE_PT_RESOURCE_IDENTIFY = "pt_resource_identify"
TASK_TYPE_SUBSCRIPTION_CHECK = "subscription_check"
TASK_TYPE_AI_RECOMMENDATION = "ai_recommendation"
TASK_TYPE_NOTIFICATION_SEND = "notification_send"
TASK_TYPE_MEDIA_FILE_SCAN = "media_file_scan"
TASK_TYPE_TASK_EXECUTION_CLEANUP = "task_execution_cleanup"
TASK_TYPE_DOWNLOAD_CREATE = "download_create"
TASK_TYPE_DOWNLOAD_STATUS_SYNC = "download_status_sync"
TASK_TYPE_UNIFIED_RESOURCE_REFRESH = "unified_resource_refresh"
TASK_TYPE_MEDIA_SERVER_WATCH_HISTORY_SYNC = "media_server_watch_history_sync"
TASK_TYPE_MEDIA_SERVER_LIBRARY_STATS_UPDATE = "media_server_library_stats_update"
TASK_TYPE_MEDIA_SERVER_LIBRARY_SYNC = "media_server_library_sync"
TASK_TYPE_MEDIA_SERVER_BATCH_REMATCH = "media_server_batch_rematch"
TASK_TYPE_TRENDING_SYNC = "trending_sync"
TASK_TYPE_TRENDING_DETAIL_SYNC = "trending_detail_sync"
TASK_TYPE_MEDIA_FILE_AUTO_ORGANIZE = "media_file_auto_organize"
TASK_TYPE_PERSON_DETAIL_SYNC = "person_detail_sync"
TASK_TYPE_CREDITS_BACKFILL = "credits_backfill"
TASK_TYPE_PERSON_MERGE = "person_merge"

TASK_TYPES = [
    TASK_TYPE_PT_RESOURCE_SYNC,
    TASK_TYPE_PT_RESOURCE_IDENTIFY,
    TASK_TYPE_SUBSCRIPTION_CHECK,
    TASK_TYPE_AI_RECOMMENDATION,
    TASK_TYPE_NOTIFICATION_SEND,
    TASK_TYPE_MEDIA_FILE_SCAN,
    TASK_TYPE_TASK_EXECUTION_CLEANUP,
    TASK_TYPE_DOWNLOAD_CREATE,
    TASK_TYPE_DOWNLOAD_STATUS_SYNC,
    TASK_TYPE_UNIFIED_RESOURCE_REFRESH,
    TASK_TYPE_MEDIA_SERVER_WATCH_HISTORY_SYNC,
    TASK_TYPE_MEDIA_SERVER_LIBRARY_STATS_UPDATE,
    TASK_TYPE_MEDIA_SERVER_LIBRARY_SYNC,
    TASK_TYPE_MEDIA_SERVER_BATCH_REMATCH,
    TASK_TYPE_TRENDING_SYNC,
    TASK_TYPE_TRENDING_DETAIL_SYNC,
    TASK_TYPE_MEDIA_FILE_AUTO_ORGANIZE,
    TASK_TYPE_PERSON_DETAIL_SYNC,
    TASK_TYPE_CREDITS_BACKFILL,
    TASK_TYPE_PERSON_MERGE,
]

TASK_TYPE_DISPLAY_NAMES = {
    TASK_TYPE_PT_RESOURCE_SYNC: "PT资源同步",
    TASK_TYPE_PT_RESOURCE_IDENTIFY: "PT资源识别",
    TASK_TYPE_SUBSCRIPTION_CHECK: "订阅检查",
    TASK_TYPE_AI_RECOMMENDATION: "AI推荐",
    TASK_TYPE_NOTIFICATION_SEND: "通知发送",
    TASK_TYPE_MEDIA_FILE_SCAN: "媒体文件扫描",
    TASK_TYPE_TASK_EXECUTION_CLEANUP: "任务执行记录清理",
    TASK_TYPE_DOWNLOAD_CREATE: "创建下载任务",
    TASK_TYPE_DOWNLOAD_STATUS_SYNC: "同步下载状态",
    TASK_TYPE_UNIFIED_RESOURCE_REFRESH: "统一资源刷新",
    TASK_TYPE_MEDIA_SERVER_WATCH_HISTORY_SYNC: "媒体服务器同步",  # 观看历史同步
    TASK_TYPE_MEDIA_SERVER_LIBRARY_STATS_UPDATE: "媒体服务器同步",  # 库统计更新
    TASK_TYPE_MEDIA_SERVER_LIBRARY_SYNC: "媒体服务器同步",  # 媒体库同步
    TASK_TYPE_MEDIA_SERVER_BATCH_REMATCH: "媒体服务器同步",  # 批量重新匹配
    TASK_TYPE_TRENDING_SYNC: "榜单同步",
    TASK_TYPE_TRENDING_DETAIL_SYNC: "榜单详情同步",
    TASK_TYPE_MEDIA_FILE_AUTO_ORGANIZE: "媒体文件自动整理",
    TASK_TYPE_PERSON_DETAIL_SYNC: "人员详情同步",
    TASK_TYPE_CREDITS_BACKFILL: "演职员关系回填",
    TASK_TYPE_PERSON_MERGE: "重复人物合并",
}

# 调度类型
SCHEDULE_TYPE_CRON = "cron"
SCHEDULE_TYPE_INTERVAL = "interval"
SCHEDULE_TYPE_ONE_TIME = "one_time"
SCHEDULE_TYPE_MANUAL = "manual"

SCHEDULE_TYPES = [
    SCHEDULE_TYPE_CRON,
    SCHEDULE_TYPE_INTERVAL,
    SCHEDULE_TYPE_ONE_TIME,
    SCHEDULE_TYPE_MANUAL,
]

SCHEDULE_TYPE_DISPLAY_NAMES = {
    SCHEDULE_TYPE_CRON: "Cron表达式",
    SCHEDULE_TYPE_INTERVAL: "固定间隔",
    SCHEDULE_TYPE_ONE_TIME: "一次性",
    SCHEDULE_TYPE_MANUAL: "手动触发",
}

# 任务执行状态
EXECUTION_STATUS_PENDING = "pending"
EXECUTION_STATUS_RUNNING = "running"
EXECUTION_STATUS_COMPLETED = "completed"
EXECUTION_STATUS_FAILED = "failed"
EXECUTION_STATUS_CANCELLED = "cancelled"
EXECUTION_STATUS_TIMEOUT = "timeout"

EXECUTION_STATUSES = [
    EXECUTION_STATUS_PENDING,
    EXECUTION_STATUS_RUNNING,
    EXECUTION_STATUS_COMPLETED,
    EXECUTION_STATUS_FAILED,
    EXECUTION_STATUS_CANCELLED,
    EXECUTION_STATUS_TIMEOUT,
]

EXECUTION_STATUS_DISPLAY_NAMES = {
    EXECUTION_STATUS_PENDING: "等待中",
    EXECUTION_STATUS_RUNNING: "执行中",
    EXECUTION_STATUS_COMPLETED: "已完成",
    EXECUTION_STATUS_FAILED: "失败",
    EXECUTION_STATUS_CANCELLED: "已取消",
    EXECUTION_STATUS_TIMEOUT: "超时",
}

# 最后运行状态（用于调度任务）
LAST_RUN_STATUS_SUCCESS = "success"
LAST_RUN_STATUS_FAILED = "failed"
LAST_RUN_STATUS_RUNNING = "running"

LAST_RUN_STATUSES = [
    LAST_RUN_STATUS_SUCCESS,
    LAST_RUN_STATUS_FAILED,
    LAST_RUN_STATUS_RUNNING,
]

# 关联实体类型
RELATED_TYPE_PT_SITE = "pt_site"
RELATED_TYPE_SUBSCRIPTION = "subscription"
RELATED_TYPE_USER = "user"
RELATED_TYPE_PT_RESOURCE = "pt_resource"

RELATED_TYPES = [
    RELATED_TYPE_PT_SITE,
    RELATED_TYPE_SUBSCRIPTION,
    RELATED_TYPE_USER,
    RELATED_TYPE_PT_RESOURCE,
]

# 默认配置
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 60  # 秒
DEFAULT_TIMEOUT = 3600  # 秒（1小时）
DEFAULT_PRIORITY = 0
